name: Create release
on:
  push:
    tags:
      - 'v*'
jobs:
  test_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
         fetch-depth: 0

      - name: Release on Powershell Gallery
        shell: pwsh
        run: |
          $ModuleVersion = "${{github.ref_name}}" -replace ('[a-zA-Z\-]', '')
          Update-ModuleManifest -Path ./HashiProd/HashiProd.psd1 -ModuleVersion $ModuleVersion
          Publish-Module -Path ./HashiProd -NuGetApiKey ${{ secrets.PSGALLERY_TOKEN }}   


    
